email: anonymous@www.com
user: first
group: first
wwwdir: /var/www/
mysql:
  host: localhost
  user: root
  password: ' '
apache:
  sites_available: '/etc/apache2/sites-available/'
  sites_enabled: '/etc/apache2/sites-enabled/'
